-- Create the links table in the public schema
CREATE TABLE IF NOT EXISTS public.links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    original_url TEXT NOT NULL,
    session_id TEXT NOT NULL,
    clicks INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create an index on session_id for faster queries
CREATE INDEX IF NOT EXISTS links_session_id_idx ON public.links(session_id);

-- Create an index on code for faster lookups
CREATE INDEX IF NOT EXISTS links_code_idx ON public.links(code);
